services:
  jekyll_red7bullet:
    image: gh-pages-env
    container_name: red7bullet_gh_pages
    restart: always
    volumes:
      - .:/srv/jekyll # 当前目录挂载到容器
    ports:
      - "8000:8000" # 映射 Jekyll 默认端口
      - "8001:8001" # 映射 Jekyll 默认端口
    command: >
      sh -c "bundle install && bundle exec jekyll serve --host 0.0.0.0 -P 8000 -I -w -l --livereload_port 8001"
